version: "3.9"
services:
  backend:
    build: ./backend
    ports:
      - "5002:5002"
    volumes:
      - ./backend:/app     # bind mount for live reload
      - /app/node_modules
    command: npm run dev
    restart: always

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "5173:5173"       # Vite dev server
    volumes:
      - ./:/app           # bind mount root
      - /app/node_modules
    command: npm run dev
    env_file:
      - ./.env         # Load environment variables from .env file   
    depends_on:
      - backend

